# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTextEdit
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 821)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/Interpreter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("/* QPushButton 样式 */\n"
"QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #0078d7;\n"
"    border: 1px solid #005bac;\n"
"    border-radius: 3px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #006cc6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #005baa;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.MeunFrame = QtWidgets.QFrame(self.centralwidget)
        self.MeunFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.MeunFrame.setStyleSheet("#MeunFrame{\n"
"    border: 1px solid #c6c6c6;\n"
"    border-radius: 3px;\n"
"    background-color: #f8f8f8;\n"
"    font-family: \'Segoe UI\', \'Helvetica Neue\', Arial, sans-serif;\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"}")
        
        self.MeunFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MeunFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MeunFrame.setObjectName("MeunFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.MeunFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.NewFilePBt = QtWidgets.QPushButton(self.MeunFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.NewFilePBt.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/新建.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NewFilePBt.setIcon(icon1)
        self.NewFilePBt.setObjectName("NewFilePBt")
        self.gridLayout.addWidget(self.NewFilePBt, 0, 0, 1, 1)
        self.CleanFilePBt = QtWidgets.QPushButton(self.MeunFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CleanFilePBt.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/清除.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CleanFilePBt.setIcon(icon2)
        self.CleanFilePBt.setObjectName("CleanFilePBt")
        self.gridLayout.addWidget(self.CleanFilePBt, 0, 3, 1, 1)
        self.ExecuteFilePBt = QtWidgets.QPushButton(self.MeunFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ExecuteFilePBt.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/执行.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExecuteFilePBt.setIcon(icon3)
        self.ExecuteFilePBt.setObjectName("ExecuteFilePBt")
        self.gridLayout.addWidget(self.ExecuteFilePBt, 0, 4, 1, 1)
        self.OpenFilePBt = QtWidgets.QPushButton(self.MeunFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.OpenFilePBt.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/打开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenFilePBt.setIcon(icon4)
        self.OpenFilePBt.setObjectName("OpenFilePBt")
        self.gridLayout.addWidget(self.OpenFilePBt, 0, 1, 1, 1)
        self.SaveFilePBt = QtWidgets.QPushButton(self.MeunFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SaveFilePBt.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveFilePBt.setIcon(icon5)
        self.SaveFilePBt.setObjectName("SaveFilePBt")
        self.gridLayout.addWidget(self.SaveFilePBt, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.MeunFrame, 0, 0, 1, 1)
        self.CodeFrame = QtWidgets.QFrame(self.centralwidget)
        self.CodeFrame.setMinimumSize(QtCore.QSize(0, 300))
        self.CodeFrame.setStyleSheet("#CodeFrame{\n"
"    border: 1px solid #c6c6c6;\n"
"    border-radius: 3px;\n"
"    background-color: #f8f8f8;\n"
"}")
        self.CodeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CodeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CodeFrame.setObjectName("CodeFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.CodeFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.CodeFrame)
        self.label_2.setStyleSheet("font-family: \'Segoe UI\', \'Helvetica Neue\', Arial, sans-serif;\n"
"font-size: 9pt;\n"
"font-weight: bold;\n"
"")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.CodeTextEdit = QTextEdit(self.CodeFrame)
        self.CodeTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.CodeTextEdit.setMaximumSize(QtCore.QSize(16777215, 750))
        self.CodeTextEdit.setStyleSheet("/* QTextEdit 样式 */\n"
"QTextEdit {\n"
"    color: #000000;\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c6c6c6;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    font-family: \'Segoe UI\', \'Helvetica Neue\', Arial, sans-serif;\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"}")
        self.CodeTextEdit.setObjectName("CodeTextEdit")
        self.gridLayout_3.addWidget(self.CodeTextEdit, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.CodeFrame, 1, 0, 1, 1)
        self.OutputFrame = QtWidgets.QFrame(self.centralwidget)
        self.OutputFrame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.OutputFrame.setStyleSheet("#OutputFrame{\n"
"    border: 1px solid #c6c6c6;\n"
"    border-radius: 3px;\n"
"    background-color: #f8f8f8;\n"
"}")
        self.OutputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OutputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OutputFrame.setObjectName("OutputFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.OutputFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.OutputFrame)
        self.label.setStyleSheet("font-family: \'Segoe UI\', \'Helvetica Neue\', Arial, sans-serif;\n"
"font-size: 9pt;\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.OutputTextEdit = QtWidgets.QTextEdit(self.OutputFrame)
        self.OutputTextEdit.setStyleSheet("/* QTextEdit 样式 */\n"
"QTextEdit {\n"
"    color: #000000;\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c6c6c6;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    font-family: \'Segoe UI\', \'Helvetica Neue\', Arial, sans-serif;\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"}")
        self.OutputTextEdit.setObjectName("OutputTextEdit")
        self.gridLayout_2.addWidget(self.OutputTextEdit, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LexerPBt = QtWidgets.QPushButton(self.OutputFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LexerPBt.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/词云.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LexerPBt.setIcon(icon6)
        self.LexerPBt.setObjectName("LexerPBt")
        self.horizontalLayout.addWidget(self.LexerPBt)
        self.SyntaxTreePBt = QtWidgets.QPushButton(self.OutputFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SyntaxTreePBt.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources/bg-tree.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SyntaxTreePBt.setIcon(icon7)
        self.SyntaxTreePBt.setObjectName("SyntaxTreePBt")
        self.horizontalLayout.addWidget(self.SyntaxTreePBt)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.OutputFrame, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CLike Interpreter"))
        self.NewFilePBt.setText(_translate("MainWindow", "新建"))
        self.CleanFilePBt.setText(_translate("MainWindow", "清除"))
        self.ExecuteFilePBt.setText(_translate("MainWindow", "执行"))
        self.OpenFilePBt.setText(_translate("MainWindow", "打开"))
        self.SaveFilePBt.setText(_translate("MainWindow", "保存"))
        self.label_2.setText(_translate("MainWindow", "Code:"))
        self.CodeTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\',\'Helvetica Neue\',\'Arial\',\'sans-serif\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Output:"))
        self.LexerPBt.setText(_translate("MainWindow", "词素序列"))
        self.SyntaxTreePBt.setText(_translate("MainWindow", "语法树"))
