# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popupwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_myPopupWidget(object):
    def setupUi(self, myPopupWidget):
        myPopupWidget.setObjectName("myPopupWidget")
        myPopupWidget.resize(566, 349)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/Interpreter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        myPopupWidget.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(myPopupWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(myPopupWidget)
        self.frame.setMinimumSize(QtCore.QSize(500, 300))
        self.frame.setStyleSheet("#frame{\n"
"    border: 1px solid #c6c6c6;\n"
"    border-radius: 3px;\n"
"    background-color: #f8f8f8;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font-family: \'Segoe UI\', \'Helvetica Neue\', Arial, sans-serif;\n"
"font-size: 9pt;\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setStyleSheet("/* QTextEdit 样式 */\n"
"QTextEdit {\n"
"    color: #000000;\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #c6c6c6;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    font-family: \'Segoe UI\', \'Helvetica Neue\', Arial, sans-serif;\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"}")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(myPopupWidget)
        QtCore.QMetaObject.connectSlotsByName(myPopupWidget)

    def retranslateUi(self, myPopupWidget):
        _translate = QtCore.QCoreApplication.translate
        myPopupWidget.setWindowTitle(_translate("myPopupWidget", "词素序列"))
        self.label.setText(_translate("myPopupWidget", "Tokens:"))
